### ISSUE TITLE
optrep module missing

### ISSUE THREAD

**Issue by heejongkim** [salilab/optimal_representation#1]
Hi,

I would like to attempt to reproduce the result from this repo but I got puzzled by the "optrep" module from IMP.
Except this repo, it seems l can't find any info about it.
It would be great if I can get some hints for setting up the local environment for this repo.

Thank you.

best,
hee jong

**Comment by shruthivis** [comment]
It is currently set to private https://github.com/salilab/optrep ; we will
enable access so that you can use it.

**Comment by heejongkim** [comment]
@shruthivis Thank you. I look forward to using it.

**Comment by shruthivis** [comment]
optrep module should now be accessible.

**Comment by heejongkim** [comment]
Thank you. I see the repo now.
will this example be compatible with IMP 2.14 or I should compile specific version with the patch from optrep?
Thank you.

**Comment by shruthivis** [comment]
Should be compatible with the latest version. Please give it a try.

**Comment by heejongkim** [comment]
I put optrep repository inside of the IMP module folder and replaced the __init__.py in dof.
After that, I compiled with python 3.8.7 with gcc+ 6.3
I had to change a bunch of print statement and some indentations but at least they got sorted out.
As I'm getting other issues, I will open the new ticket for that. 
Thanks.
